# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger
    pod 'FirebaseCore'
    pod 'FirebaseAuth'
    pod 'FirebaseDatabase'

  # Pods for Facebook Auth
    pod 'FBSDKLoginKit'

  # Pods for Google Auth
    pod 'GoogleSignIn'
end
